# Generated by Django 2.0 on 2018-09-05 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('info', models.TextField()),
                ('meta', models.TextField()),
                ('preview_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoScene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('preview_url', models.URLField(null=True)),
                ('meta', models.TextField()),
                ('tags', models.ManyToManyField(to='material.Tag')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='material.Video')),
            ],
        ),
    ]
