# Generated by Django 2.1.2 on 2018-10-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('text', models.TextField()),
                ('scenes', models.TextField()),
                ('meta', models.TextField()),
            ],
        ),
    ]
