# Generated by Django 2.1.2 on 2018-10-19 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0002_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('wait', 'wait'), ('live', 'live'), ('done', 'done')], default='wait', max_length=1024)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'verbose_name': '精彩錦集', 'verbose_name_plural': '精彩錦集'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': '影片', 'verbose_name_plural': '影片'},
        ),
        migrations.AlterModelOptions(
            name='videoscene',
            options={'verbose_name': '精彩片段', 'verbose_name_plural': '精彩片段'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='meta',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='streaming',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='material.Video'),
        ),
    ]
