# Generated by Django 2.1.2 on 2018-10-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_auto_20181019_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
