# Generated by Django 2.1.2 on 2018-10-19 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0005_video_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaming',
            name='url',
            field=models.URLField(default='http://104.199.250.233:8000/material/video/streaming/223.m3u8?start_time=2018-09-01T00:00:00&cycle_seconds=7200'),
            preserve_default=False,
        ),
    ]
