# Generated by Django 2.1.2 on 2018-10-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0006_streaming_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaming',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('wait', 'wait'), ('live', 'live'), ('done', 'done'), ('fails', 'fails')], default='wait', max_length=1024),
        ),
    ]
