# Generated by Django 2.1.2 on 2018-10-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0008_auto_20181020_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='streaming',
            name='meta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
