# Generated by Django 2.1.2 on 2018-10-21 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0010_auto_20181021_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaming',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
