# Generated by Django 2.0 on 2018-10-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0011_auto_20181021_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('wait', 'wait'), ('done', 'done'), ('fail', 'fail')], default='done', max_length=1024),
            preserve_default=False,
        ),
    ]
