# Generated by Django 2.0 on 2018-10-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0012_collection_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaming',
            name='url',
            field=models.CharField(max_length=4096),
        ),
    ]
