# Generated by Django 2.1.2 on 2018-10-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0015_collection_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaming',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
