# Generated by Django 2.1.2 on 2018-11-02 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0017_auto_20181026_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='UncheckVideoScene',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('material.videoscene',),
        ),
        migrations.AddField(
            model_name='videoscene',
            name='status',
            field=models.CharField(choices=[('init', 'init'), ('approve', 'approve'), ('reject', 'reject')], default='init', max_length=256),
        ),
    ]
