# Generated by Django 2.1.2 on 2018-11-19 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cba', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatEvent',
            fields=[
                ('id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('_messages', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatPlayDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=1024)),
                ('detail_id', models.CharField(max_length=1024)),
                ('event', models.CharField(max_length=1024)),
                ('detail', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='StatPlayer',
            fields=[
                ('id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatTeam',
            fields=[
                ('location', models.CharField(max_length=1024)),
                ('nick_name', models.CharField(max_length=1024)),
                ('abbreviation', models.CharField(max_length=1024)),
                ('id', models.CharField(max_length=1024, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='statplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cba.StatTeam'),
        ),
        migrations.AlterUniqueTogether(
            name='statplaydetail',
            unique_together={('event_id', 'detail_id')},
        ),
        migrations.AddField(
            model_name='statevent',
            name='away_Team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='cba.StatTeam'),
        ),
        migrations.AddField(
            model_name='statevent',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='cba.StatTeam'),
        ),
    ]
